config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get 'vote/create'
  get 'vote/destroy'
  get 'locations/new'
  get 'courses/new'
  post 'courses/new'
  get 'categories/new'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  get  '/contact', to: 'contacts#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  resources :send_feedbacks, only: [:edit]
  resources :courses do
	resources :votes, only: [:create, :destroy, :update] do
		collection do
			get 'remove_all'
		end
	end
  end
  resources :categories
  resources :locations
  resources :users

  if Rails.env.development?
	get '404', :to => 'application#page_not_found'
	get '422', :to => 'application#server_error'
	get '500', :to => 'application#server_error'
  end

  if Rails.env.production?
   	get '404', :to => 'application#page_not_found'
   	get '422', :to => 'application#server_error'
   	get '500', :to => 'application#server_error'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>About | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      This is the assignment for RMIT Rapid Application Development course - semester 1 2019
    </p>
  </body>
</html>

app/views/static_pages/help.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Help | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="https://www.railstutorial.org/help">Rails Tutorial help
      page</a>.
      To get help on this sample app, see the
      <a href="https://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Your Course App</h1>

  <h2>
    This is the home page for the
    RAD Assignment
  </h2>

  <%= link_to "Sign up now", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<div class="row">
  <div class="column">
    <h3>View Course as Guest User</h3>
    <p>Browse and view courses as a guest and sign up later</p>
    <%= link_to "Browse all courses", courses_path, class: "btn btn-lg btn-primary" %>
  </div>
  <div class="column">
    <h3>Sign in to your account</h3>
    <p>Update your courses, rate courses, view coordinator infomatinos</p>
    <%= link_to "Log in to your account", login_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>