config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get 'vote/create'
  get 'vote/destroy'
  get 'locations/new'
  get 'courses/new'
  post 'courses/new'
  get 'categories/new'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  get  '/contact', to: 'contacts#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  resources :send_feedbacks, only: [:edit]
  resources :courses do
	resources :votes, only: [:create, :destroy, :update] do
		collection do
			get 'remove_all'
		end
	end
  end
  resources :categories
  resources :locations
  resources :users

  if Rails.env.development?
	get '404', :to => 'application#page_not_found'
	get '422', :to => 'application#server_error'
	get '500', :to => 'application#server_error'
  end

  if Rails.env.production?
   	get '404', :to => 'application#page_not_found'
   	get '422', :to => 'application#server_error'
   	get '500', :to => 'application#server_error'
  end
end

app/models/contact.rb
class Contact < ApplicationRecord

	validates :message, :presence => :true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(feedback_params)
    
    if @contact.save
      ContactsMailer.send_feedback(@contact).deliver
      flash[:success] = "Thank you for your feedback!"
      redirect_to :courses
    else
      render :new
    end
  end

def thanks
  end
 private 
  def feedback_params
	params.require(:contact).permit(:name, :email, :message)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Email (optional)" %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit "Send", class: 'btn btn-primary btn-sm'%>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>Contact us</h1>
<h4>Send Us A Message</h4>

<%= render 'form' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>