config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get 'vote/create'
  get 'vote/destroy'
  get 'locations/new'
  get 'courses/new'
  post 'courses/new'
  get 'categories/new'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  get  '/contact', to: 'contacts#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  resources :send_feedbacks, only: [:edit]
  resources :courses do
	resources :votes, only: [:create, :destroy, :update] do
		collection do
			get 'remove_all'
		end
	end
  end
  resources :categories
  resources :locations
  resources :users

  if Rails.env.development?
	get '404', :to => 'application#page_not_found'
	get '422', :to => 'application#server_error'
	get '500', :to => 'application#server_error'
  end

  if Rails.env.production?
   	get '404', :to => 'application#page_not_found'
   	get '422', :to => 'application#server_error'
   	get '500', :to => 'application#server_error'
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", new_contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in? %>
    	<%= link_to "your course", courses_path , id: "logo" %>
    <% else %>
    	<%= link_to "your course", root_path, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-crosshairs"></i> Category <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Show All", courses_path %></li>
            <% (Category.all).each do |cat| %>
            <li><%= link_to cat.category, courses_path(:category=>cat.category)  %></li>
            <% end %>
            <% if logged_in? %>
              <li><%= link_to "New Category", new_category_path %></li>
            <% end %>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-crosshairs"></i> Locations <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Show All", courses_path %></li>
            <% (Location.all).each do |loc| %>
            <li><%= link_to loc.location, courses_path(:location=>loc.location)  %></li>
            <% end %>
            <% if logged_in? %>
              <li><%= link_to "New Location", new_location_path %></li>
            <% end %>
          </ul>
        </li>


        <% if logged_in? %>
          <li><%= link_to "New Course", new_course_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= @current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= action_name.titleize %> :: <%= site_name %></title>
  <%= csrf_meta_tags %>
  <style>
    body {
        background: #fff;
        font-family: Helvetica, Arial, Sans-Serif;
        font-size: 14px;
    }
    .error_container {
        display: block;
        margin: auto;
        margin: 10% auto 0 auto;
        width: 40%;
    }
    .error_container .error {
        display: block; 
        text-align: center;
    }
    .error_container .error img {
        display: block;
        margin: 0 auto 25px auto;
    }
    .error_container .message strong {
        font-weight: bold;
        color: #f00;
    }
    .error_container .contact_info {
        display: block;
        text-align: center;
        margin: 25px 0 0 0;
    }
    .error_container .contact_info a {
        display: inline-block;
        margin: 0 5px;
        opacity: 0.4;
        transition: opacity 0.15s ease;
    }
    .error_container .contact_info a:hover {
        opacity: 0.8;
    }
  </style>
</head>
<body>
  <div class="error_container">
      <%= yield %>
  </div>
</body>
</html>